/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.macpollo.front;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author cass465
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaPrincipal() {
        initComponents();

        //Icono del frame
        this.setIconImage(new ImageIcon("src/main/java/com/macpollo/images/icons/MacPolloIcon.png").getImage());

        //Centrar ventana en pantalla
        setLocationRelativeTo(null);
        
        fechaHoyTxt.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));

        ImageIcon imagen = new ImageIcon("src/main/java/com/macpollo/images/icons/MacPolloN1.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(macPolloN1L.getWidth(), macPolloN1L.getHeight(), Image.SCALE_DEFAULT));
        macPolloN1L.setIcon(icono);

        Icon gestionClientesIcon = new ImageIcon(new ImageIcon("src/main/java/com/macpollo/images/icons/GestionClientes.png").getImage());
        gestionClientesBtn.setIcon(gestionClientesIcon);

        Icon gestionOperadorIcon = new ImageIcon(new ImageIcon("src/main/java/com/macpollo/images/icons/GestionOperador.png").getImage());
        gestionOperadorBtn.setIcon(gestionOperadorIcon);

        Icon gestionHorasIcon = new ImageIcon(new ImageIcon("src/main/java/com/macpollo/images/icons/GestionHoras.png").getImage());
        gestionHorasBtn.setIcon(gestionHorasIcon);

        Icon gestionCampaniasIcon = new ImageIcon(new ImageIcon("src/main/java/com/macpollo/images/icons/GestionCampania.png").getImage());
        gestionCampaniasBtn.setIcon(gestionCampaniasIcon);

        Icon cargueCampaniasIcon = new ImageIcon(new ImageIcon("src/main/java/com/macpollo/images/icons/Upload.png").getImage());
        cargueCampaniasBtn.setIcon(cargueCampaniasIcon);

        //opcionesEstadisticasPane.setEnabled(false);
        opcionesEstadisticasPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesPane = new javax.swing.JTabbedPane();
        inicioPanel = new javax.swing.JPanel();
        presentacionPanel = new javax.swing.JPanel();
        macPolloN1L = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechaHoyPanel = new javax.swing.JPanel();
        fechaHoyTxt = new javax.swing.JTextField();
        teleMercadeoPanel = new javax.swing.JPanel();
        clientesTMPanel = new javax.swing.JPanel();
        fechaCampaniaPanel = new javax.swing.JPanel();
        fechaCampaniaTxt = new javax.swing.JTextField();
        tipoMarcacionPanel = new javax.swing.JPanel();
        tipoMarcacionTxt = new javax.swing.JTextField();
        marcacionAutBtn = new javax.swing.JButton();
        retomarGestionBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesPorLlamarTable = new javax.swing.JTable();
        clientesPorLlamarL = new javax.swing.JLabel();
        clientesPorLlamarL1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientesLlamarMasTardeTable = new javax.swing.JTable();
        crearClienteBtn = new javax.swing.JButton();
        cancelarLlamadaBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        callCenterInBoundPanel = new javax.swing.JPanel();
        pedidosInBoundPanel = new javax.swing.JPanel();
        estadisticasPanel = new javax.swing.JPanel();
        opcionesPanel = new javax.swing.JPanel();
        gestionClientesBtn = new javax.swing.JButton();
        gestionClientesL = new javax.swing.JLabel();
        gestionOperadorBtn = new javax.swing.JButton();
        gestionOperadorL = new javax.swing.JLabel();
        gestionHorasL = new javax.swing.JLabel();
        gestionCampaniasL = new javax.swing.JLabel();
        cargueCampaniasL = new javax.swing.JLabel();
        gestionHorasBtn = new javax.swing.JButton();
        gestionCampaniasBtn = new javax.swing.JButton();
        cargueCampaniasBtn = new javax.swing.JButton();
        opcionesEstadisticasPane = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        opcionesPane.setToolTipText("");
        opcionesPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opcionesPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                opcionesPaneStateChanged(evt);
            }
        });
        opcionesPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionesPaneMouseClicked(evt);
            }
        });

        inicioPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel4.setText("Sistema Integrado Distribuidoras");

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setText("Módulo Call Center");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Propiedad Intelectual de Avidesa Mac Pollo S.A.");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Derechos Reservados");

        javax.swing.GroupLayout presentacionPanelLayout = new javax.swing.GroupLayout(presentacionPanel);
        presentacionPanel.setLayout(presentacionPanelLayout);
        presentacionPanelLayout.setHorizontalGroup(
            presentacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentacionPanelLayout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addGroup(presentacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentacionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentacionPanelLayout.createSequentialGroup()
                        .addGroup(presentacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(205, 205, 205))))
            .addGroup(presentacionPanelLayout.createSequentialGroup()
                .addGroup(presentacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(presentacionPanelLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(macPolloN1L, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(presentacionPanelLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        presentacionPanelLayout.setVerticalGroup(
            presentacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentacionPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(macPolloN1L, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );

        fechaHoyPanel.setBackground(new java.awt.Color(255, 255, 255));
        fechaHoyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha del Proceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N

        fechaHoyTxt.setEditable(false);
        fechaHoyTxt.setBackground(new java.awt.Color(255, 255, 153));
        fechaHoyTxt.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        fechaHoyTxt.setText("dd/MM/yyyy");

        javax.swing.GroupLayout fechaHoyPanelLayout = new javax.swing.GroupLayout(fechaHoyPanel);
        fechaHoyPanel.setLayout(fechaHoyPanelLayout);
        fechaHoyPanelLayout.setHorizontalGroup(
            fechaHoyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechaHoyPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fechaHoyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        fechaHoyPanelLayout.setVerticalGroup(
            fechaHoyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechaHoyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fechaHoyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inicioPanelLayout = new javax.swing.GroupLayout(inicioPanel);
        inicioPanel.setLayout(inicioPanelLayout);
        inicioPanelLayout.setHorizontalGroup(
            inicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioPanelLayout.createSequentialGroup()
                .addGroup(inicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicioPanelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(presentacionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicioPanelLayout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(fechaHoyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        inicioPanelLayout.setVerticalGroup(
            inicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(fechaHoyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(presentacionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        opcionesPane.addTab("Inicio", inicioPanel);

        teleMercadeoPanel.setBackground(new java.awt.Color(255, 255, 255));

        fechaCampaniaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Campaña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N

        fechaCampaniaTxt.setEditable(false);
        fechaCampaniaTxt.setBackground(new java.awt.Color(255, 255, 153));
        fechaCampaniaTxt.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        fechaCampaniaTxt.setText("dd/MM/yyyy");

        javax.swing.GroupLayout fechaCampaniaPanelLayout = new javax.swing.GroupLayout(fechaCampaniaPanel);
        fechaCampaniaPanel.setLayout(fechaCampaniaPanelLayout);
        fechaCampaniaPanelLayout.setHorizontalGroup(
            fechaCampaniaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechaCampaniaPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(fechaCampaniaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        fechaCampaniaPanelLayout.setVerticalGroup(
            fechaCampaniaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechaCampaniaPanelLayout.createSequentialGroup()
                .addComponent(fechaCampaniaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        tipoMarcacionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Marcación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N

        tipoMarcacionTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tipoMarcacionTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipoMarcacionTxt.setText("Automática");

        javax.swing.GroupLayout tipoMarcacionPanelLayout = new javax.swing.GroupLayout(tipoMarcacionPanel);
        tipoMarcacionPanel.setLayout(tipoMarcacionPanelLayout);
        tipoMarcacionPanelLayout.setHorizontalGroup(
            tipoMarcacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoMarcacionPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tipoMarcacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        tipoMarcacionPanelLayout.setVerticalGroup(
            tipoMarcacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoMarcacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoMarcacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        marcacionAutBtn.setText("Iniciar Marcación Autmática");

        retomarGestionBtn.setText("Retomar Gestión");
        retomarGestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retomarGestionBtnActionPerformed(evt);
            }
        });

        clientesPorLlamarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código SAP", "Teléfono", "Cliente", "Nombre Cliente", "Pto Vta", "Almacén", "Dirección", "Barrio", "Horario Llamada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(clientesPorLlamarTable);

        clientesPorLlamarL.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        clientesPorLlamarL.setText("Clientes Pendientes Por Llamar");

        clientesPorLlamarL1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        clientesPorLlamarL1.setText("Clientes Por Llamar Más Tarde");

        clientesLlamarMasTardeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código SAP", "Teléfono", "Cliente", "Nombre Cliente", "Pto Vta", "Almacén", "Dirección", "Barrio", "Horario Llamada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(clientesLlamarMasTardeTable);

        crearClienteBtn.setText("Crear Cliente");

        cancelarLlamadaBtn.setText("Cancelar Llamada");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Por Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N

        jLabel2.setText("Pedidos");

        jLabel3.setText("Llamadas");

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");

        jTextField2.setBackground(new java.awt.Color(255, 255, 153));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consolidado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N

        jTextField3.setBackground(new java.awt.Color(255, 255, 153));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");

        jLabel7.setText("Pedidos");

        jLabel8.setText("Llamadas");

        jTextField4.setBackground(new java.awt.Color(255, 255, 153));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Por Llamar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N

        jLabel9.setText("Por Usuario");

        jTextField5.setBackground(new java.awt.Color(255, 255, 153));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");

        jLabel10.setText("Consolidado");

        jTextField6.setBackground(new java.awt.Color(255, 255, 153));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jTextField5))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout clientesTMPanelLayout = new javax.swing.GroupLayout(clientesTMPanel);
        clientesTMPanel.setLayout(clientesTMPanelLayout);
        clientesTMPanelLayout.setHorizontalGroup(
            clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesTMPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(clientesTMPanelLayout.createSequentialGroup()
                        .addComponent(clientesPorLlamarL1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(clientesTMPanelLayout.createSequentialGroup()
                        .addGroup(clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientesPorLlamarL)
                            .addGroup(clientesTMPanelLayout.createSequentialGroup()
                                .addComponent(fechaCampaniaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(retomarGestionBtn)
                                    .addGroup(clientesTMPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(crearClienteBtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marcacionAutBtn)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesTMPanelLayout.createSequentialGroup()
                                        .addComponent(cancelarLlamadaBtn)
                                        .addGap(28, 28, 28)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoMarcacionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        clientesTMPanelLayout.setVerticalGroup(
            clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesTMPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientesTMPanelLayout.createSequentialGroup()
                        .addGroup(clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaCampaniaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(clientesTMPanelLayout.createSequentialGroup()
                                .addGroup(clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marcacionAutBtn)
                                    .addComponent(retomarGestionBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(crearClienteBtn)
                                    .addComponent(cancelarLlamadaBtn)))
                            .addComponent(tipoMarcacionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clientesPorLlamarL))
                    .addGroup(clientesTMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientesPorLlamarL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout teleMercadeoPanelLayout = new javax.swing.GroupLayout(teleMercadeoPanel);
        teleMercadeoPanel.setLayout(teleMercadeoPanelLayout);
        teleMercadeoPanelLayout.setHorizontalGroup(
            teleMercadeoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teleMercadeoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientesTMPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        teleMercadeoPanelLayout.setVerticalGroup(
            teleMercadeoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teleMercadeoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientesTMPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        opcionesPane.addTab("Tele Mercadeo", teleMercadeoPanel);

        callCenterInBoundPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout callCenterInBoundPanelLayout = new javax.swing.GroupLayout(callCenterInBoundPanel);
        callCenterInBoundPanel.setLayout(callCenterInBoundPanelLayout);
        callCenterInBoundPanelLayout.setHorizontalGroup(
            callCenterInBoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
        );
        callCenterInBoundPanelLayout.setVerticalGroup(
            callCenterInBoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        opcionesPane.addTab("Call Center InBound", callCenterInBoundPanel);

        pedidosInBoundPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pedidosInBoundPanelLayout = new javax.swing.GroupLayout(pedidosInBoundPanel);
        pedidosInBoundPanel.setLayout(pedidosInBoundPanelLayout);
        pedidosInBoundPanelLayout.setHorizontalGroup(
            pedidosInBoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
        );
        pedidosInBoundPanelLayout.setVerticalGroup(
            pedidosInBoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        opcionesPane.addTab("Pedidos InBound", pedidosInBoundPanel);

        estadisticasPanel.setBackground(new java.awt.Color(255, 255, 255));

        opcionesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N

        gestionClientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionClientesBtnActionPerformed(evt);
            }
        });

        gestionClientesL.setText("Gestión de Clientes");

        gestionOperadorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionOperadorBtnActionPerformed(evt);
            }
        });

        gestionOperadorL.setText("Gestión por Operador");

        gestionHorasL.setText("Gestión por Horas");

        gestionCampaniasL.setText("Gestión Campañas");

        cargueCampaniasL.setText("Cargue por Campañas");

        gestionHorasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionHorasBtnActionPerformed(evt);
            }
        });

        gestionCampaniasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionCampaniasBtnActionPerformed(evt);
            }
        });

        cargueCampaniasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargueCampaniasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesPanelLayout = new javax.swing.GroupLayout(opcionesPanel);
        opcionesPanel.setLayout(opcionesPanelLayout);
        opcionesPanelLayout.setHorizontalGroup(
            opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(gestionClientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(gestionOperadorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(gestionHorasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(gestionCampaniasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(cargueCampaniasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gestionClientesL)
                .addGap(18, 18, 18)
                .addComponent(gestionOperadorL)
                .addGap(18, 18, 18)
                .addComponent(gestionHorasL, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gestionCampaniasL)
                .addGap(18, 18, 18)
                .addComponent(cargueCampaniasL)
                .addGap(89, 89, 89))
        );
        opcionesPanelLayout.setVerticalGroup(
            opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gestionClientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestionOperadorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestionHorasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestionCampaniasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargueCampaniasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gestionClientesL)
                    .addComponent(gestionOperadorL)
                    .addComponent(gestionHorasL)
                    .addComponent(gestionCampaniasL)
                    .addComponent(cargueCampaniasL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        opcionesEstadisticasPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                opcionesEstadisticasPaneStateChanged(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        opcionesEstadisticasPane.addTab("Gestión de Clientes", jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        opcionesEstadisticasPane.addTab("Gestión por Operador", jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        opcionesEstadisticasPane.addTab("Gestión por Horas", jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        opcionesEstadisticasPane.addTab("Gestion Campañas", jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        opcionesEstadisticasPane.addTab("Cargue por Campañas", jPanel15);

        javax.swing.GroupLayout estadisticasPanelLayout = new javax.swing.GroupLayout(estadisticasPanel);
        estadisticasPanel.setLayout(estadisticasPanelLayout);
        estadisticasPanelLayout.setHorizontalGroup(
            estadisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadisticasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(estadisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(estadisticasPanelLayout.createSequentialGroup()
                        .addComponent(opcionesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(opcionesEstadisticasPane))
                .addContainerGap())
        );
        estadisticasPanelLayout.setVerticalGroup(
            estadisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadisticasPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(opcionesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesEstadisticasPane, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        opcionesPane.addTab("Estadísticas", estadisticasPanel);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        opcionesPane.addTab("Procesos Especiales", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        opcionesPane.addTab("Cambio de Clave", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        opcionesPane.addTab("Soporte Técnico", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        opcionesPane.addTab("Salir", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionesPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionesPane, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionesPaneMouseClicked

    }//GEN-LAST:event_opcionesPaneMouseClicked

    private void opcionesPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_opcionesPaneStateChanged
        if (opcionesPane.getSelectedIndex() == 4) {
            opcionesEstadisticasPane.setVisible(false);
        }
        
        if (opcionesPane.getSelectedIndex() == 8) {
            this.dispose();
            new VentanaCall().setVisible(true);
        }
    }//GEN-LAST:event_opcionesPaneStateChanged

    private void habilitarOpcionEstadísticas(int opcion) {
        opcionesEstadisticasPane.setVisible(true);
        
        for (int i = 0; i <= 4; i++) {
            if (i != opcion) {
                opcionesEstadisticasPane.setEnabledAt(i, false);
            }
        }
        
        opcionesEstadisticasPane.setEnabledAt(opcion, true);
        opcionesEstadisticasPane.setSelectedIndex(opcion);
    }
    
    private void gestionClientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionClientesBtnActionPerformed
        habilitarOpcionEstadísticas(0);
    }//GEN-LAST:event_gestionClientesBtnActionPerformed

    private void gestionOperadorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionOperadorBtnActionPerformed
        habilitarOpcionEstadísticas(1);
    }//GEN-LAST:event_gestionOperadorBtnActionPerformed

    private void gestionHorasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionHorasBtnActionPerformed
        habilitarOpcionEstadísticas(2);
    }//GEN-LAST:event_gestionHorasBtnActionPerformed

    private void gestionCampaniasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionCampaniasBtnActionPerformed
        habilitarOpcionEstadísticas(3);
    }//GEN-LAST:event_gestionCampaniasBtnActionPerformed

    private void cargueCampaniasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargueCampaniasBtnActionPerformed
        habilitarOpcionEstadísticas(4);
    }//GEN-LAST:event_cargueCampaniasBtnActionPerformed

    private void opcionesEstadisticasPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_opcionesEstadisticasPaneStateChanged
        
    }//GEN-LAST:event_opcionesEstadisticasPaneStateChanged

    private void retomarGestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retomarGestionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retomarGestionBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel callCenterInBoundPanel;
    private javax.swing.JButton cancelarLlamadaBtn;
    private javax.swing.JButton cargueCampaniasBtn;
    private javax.swing.JLabel cargueCampaniasL;
    private javax.swing.JTable clientesLlamarMasTardeTable;
    private javax.swing.JLabel clientesPorLlamarL;
    private javax.swing.JLabel clientesPorLlamarL1;
    private javax.swing.JTable clientesPorLlamarTable;
    private javax.swing.JPanel clientesTMPanel;
    private javax.swing.JButton crearClienteBtn;
    private javax.swing.JPanel estadisticasPanel;
    private javax.swing.JPanel fechaCampaniaPanel;
    private javax.swing.JTextField fechaCampaniaTxt;
    private javax.swing.JPanel fechaHoyPanel;
    private javax.swing.JTextField fechaHoyTxt;
    private javax.swing.JButton gestionCampaniasBtn;
    private javax.swing.JLabel gestionCampaniasL;
    private javax.swing.JButton gestionClientesBtn;
    private javax.swing.JLabel gestionClientesL;
    private javax.swing.JButton gestionHorasBtn;
    private javax.swing.JLabel gestionHorasL;
    private javax.swing.JButton gestionOperadorBtn;
    private javax.swing.JLabel gestionOperadorL;
    private javax.swing.JPanel inicioPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel macPolloN1L;
    private javax.swing.JButton marcacionAutBtn;
    private javax.swing.JTabbedPane opcionesEstadisticasPane;
    private javax.swing.JTabbedPane opcionesPane;
    private javax.swing.JPanel opcionesPanel;
    private javax.swing.JPanel pedidosInBoundPanel;
    private javax.swing.JPanel presentacionPanel;
    private javax.swing.JButton retomarGestionBtn;
    private javax.swing.JPanel teleMercadeoPanel;
    private javax.swing.JPanel tipoMarcacionPanel;
    private javax.swing.JTextField tipoMarcacionTxt;
    // End of variables declaration//GEN-END:variables
}
